### ISSUE TITLE
Uncaught Error: attempted to add non-function middleware

### ISSUE THREAD

**Issue by pablolee89** [segmentio/consent-manager#206]
I'm getting this error in the browser console whenever analytics tries to load:

```
Uncaught Error: attempted to add non-function middleware
    at t.exports.SourceMiddlewareChain.e.add (analytics.min.js:5:4212)
    at i.addSourceMiddleware (analytics.min.js:4:18273)
    at i.addSourceMiddleware (analytics.min.js:18:12393)
    at Object.<anonymous> (analytics.min.js:1:7218)
    at Object.3../analytics (analytics.min.js:1:7253)
    at i (analytics.min.js:1:341)
    at e (analytics.min.js:1:499)
    at analytics.min.js:1:527
```

We are using the `ConsentManager` implementation from `@segment/consent-manager` v5.4.0

```
const ConsentManagerWrapper: FC = () => {
  const { colors } = useContext(ThemeContext);
  const { hasCheckedSession, user } = usePlayUser();
  if ((hasCheckedSession && user) || !hasCheckedSession) return null;

  const inCA = inRegions(['CA']);
  const inEU = inRegions(['EU']);

  const shouldRequireConsent = inRegions(['CA', 'EU']);

  // CCPA compliance
  const caDefaultPreferences = {
    advertising: false,
    marketingAndAnalytics: true,
    functional: true,
  };

  // GDPR compliance
  const euDefaultPreferences = {
    advertising: false,
    marketingAndAnalytics: false,
    functional: false,
  };

  const caCloseBehavior = (): CategoryPreferences => {
    return caDefaultPreferences;
  };
  const euCloseBehavior = inEU() ? 'deny' : 'accept';
  const closeBehavior = inCA() ? caCloseBehavior : euCloseBehavior;

  const euInitialPreferences = inEU() ? euDefaultPreferences : undefined;
  const initialPreferences = inCA() ? caDefaultPreferences : euInitialPreferences;

  const preferencesDialogTitle = 'Website Data Collection Preferences';
  const preferencesDialogContent =
    'We use data collected by cookies and JavaScript libraries to improve your browsing experience, analyze site traffic, deliver personalized advertisements, and increase the overall performance of our site.';
  const cancelDialogTitle = 'Are you sure you want to cancel?';
  const cancelDialogContent =
    'Your preferences have not been saved. By continuing to use our website, you՚re agreeing to our Website Data Collection Policy.';

  return (
    <Wrapper id="consent-wrapper" role="region" aria-label="cookie consent banner">
      <ConsentManager
        writeKey={key}
        bannerContent={bannerContent}
        bannerSubContent={bannerButton}
        preferencesDialogTitle={preferencesDialogTitle}
        preferencesDialogContent={preferencesDialogContent}
        cancelDialogTitle={cancelDialogTitle}
        cancelDialogContent={cancelDialogContent}
        closeBehavior={closeBehavior}
        shouldRequireConsent={shouldRequireConsent}
        initialPreferences={initialPreferences}
        bannerBackgroundColor={colors.nearWhite}
        bannerTextColor={colors.darkGray}
      />
    </Wrapper>
  );
```

and here is our analytics.js file:

```
export function decorateWindow() {
  // eslint-disable-next-line no-multi-assign
  const analytics = (window.analytics = window.analytics || []);
  if (analytics.initialize) return;

  if (analytics.invoked) {
    if (window.console && console.error) {
      console.error('Segment snippet included twice.');
    }
    return;
  }
  // Invoked flag, to make sure the snippet
  // is never invoked twice.
  analytics.invoked = true;
  // A list of the methods in Analytics.js to stub.
  analytics.methods = [
    'trackSubmit',
    'trackClick',
    'trackLink',
    'trackForm',
    'pageview',
    'identify',
    'reset',
    'group',
    'track',
    'ready',
    'alias',
    'debug',
    'page',
    'once',
    'off',
    'on',
    'addSourceMiddleware',
    'addIntegrationMiddleware',
    'setAnonymousId',
    'addDestinationMiddleware',
  ];

  // Define a factory to create stubs. These are placeholders
  // for methods in Analytics.js so that you never have to wait
  // for it to load to actually record data. The `method` is
  // stored as the first argument, so we can replay the data.
  analytics.factory = method => {
    return () => {
      // eslint-disable-next-line prefer-rest-params
      const args = Array.prototype.slice.call(arguments);
      args.unshift(method);
      analytics.push(args);
      return analytics;
    };
  };
  for (let i = 0; i < analytics.methods.length; i++) {
    const key = analytics.methods[i];
    analytics[key] = analytics.factory(key);
  }

  analytics.load = (key, options) => {
    // Create an async script element based on your key.
    const script = document.createElement('script');
    script.type = 'text/javascript';
    script.id = 'segment_analytics';
    script.async = true;
    script.src = `${
      document.location.protocol === 'https:' ? 'https://' : 'http://'
    }cdn.segment.com/analytics.js/v1/${key}/analytics.min.js`;

    // Insert our script next to the first script element.
    const first = document.getElementsByTagName('script')[0];
    first.parentNode.insertBefore(script, first);
    // eslint-disable-next-line no-underscore-dangle
    analytics._loadOptions = options;
  };
  analytics.SNIPPET_VERSION = '4.1.0';
}
```

**Comment by nd4p90x** [comment]
We are looking into your issue and will get back with you shortly.  Thank you

**Comment by emont01** [comment]
@pablolee89 I had a similar situation because I have provided a value instead of a function for one of the properties of `<ConsentManager />`

Here is an example with the incorrect definition for shouldRequireConsent
``` jsx
return (
  <div>
      <ConsentManager
        writeKey="MY_WRITE_KEY"
        shouldRequireConsent={true}
        .....
      />
      <button type="button" onClick={openConsentManager}>
        Website Data Collection Preferences
      </button>
  </div>
)
```

After changing the code above as follows everything worked as expected
``` jsx
return (
  <div>
      <ConsentManager
        writeKey="MY_WRITE_KEY"
        shouldRequireConsent={() => true}
        .....
      />
      <button type="button" onClick={openConsentManager}>
        Website Data Collection Preferences
      </button>
  </div>
)
```

**Comment by nd4p90x** [comment]
@pablolee89 If this continues to be an issue, feel free to re-open or start a new thread.  Thank you.
