### ISSUE TITLE
Cannot read properties of undefined (reading 'addSourceMiddleware')

### ISSUE THREAD

**Issue by brettdewoody** [segmentio/consent-manager#207]
Using the latest Segment ConsentManager component in React 17.0.2.

After clicking allow on the consent manager I receive the following error in the console. 

If I select Deny All, everything continues to work. But allowing cookies causes the error below.

```
react-dom.development.js:11340 Uncaught TypeError: Cannot read properties of undefined (reading 'addSourceMiddleware')
    at conditionallyLoadAnalytics (analytics.ts:91:18)
    at ConsentManagerBuilder3.<anonymous> (index.tsx:332:9)
    at getStateFromUpdate (react-dom.development.js:12102:35)
    at processUpdateQueue (react-dom.development.js:12250:20)
    at updateClassInstance (react-dom.development.js:13013:3)
    at updateClassComponent (react-dom.development.js:17432:20)
    at beginWork (react-dom.development.js:19073:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
```

I implement the ConsentManager with 

```
<ConsentManager
        writeKey={SEGMENT_WRITE_KEY}
        shouldRequireConsent={inEU}
        bannerContent={bannerContent}
        bannerSubContent={bannerSubContent}
        preferencesDialogTitle={preferencesDialogTitle}
        preferencesDialogContent={preferencesDialogContent}
        cancelDialogTitle={cancelDialogTitle}
        cancelDialogContent={cancelDialogContent}
        bannerActionsBlock={bannerActionsBlock}
/>
```

**Comment by alexhansonsmith** [comment]
@brettdewoody, we are experiencing the same issue. I have just seen this in the docs:

"Breaking Changes: Version 5.0.0 and above require that your analytics.js snippet include the method addSourceMiddleware in the analytics.methods array"

`analytics.methods = [
  'trackSubmit',
  'trackClick',
  'trackLink',
  'trackForm',
  'pageview',
  'identify',
  'reset',
  'group',
  'track',
  'ready',
  'alias',
  'debug',
  'page',
  'once',
  'off',
  'on',
  'addSourceMiddleware' // This method is necessary for Consent Manager to forward consent metadata.
]`

Hope this helps

**Comment by brettdewoody** [comment]
@alexhansonsmith Thank you, that at least gives a direction. I'm using the `ConsentManager` component, and don't see an option to define the methods. Have you been able to solve this?

**Comment by brettdewoody** [comment]
@nd4p90x Are there any examples showing how to use the ConsentManager component - I'm still getting the error above even when trying to use the <script>.

**Comment by emont01** [comment]
this seems related to issue #202

**Comment by nd4p90x** [comment]
Please feel free to re-open or start a new thread if necessary, thank you!

**Comment by mateusz-chuchro** [comment]
I got the same issue and just for the future: even if you use ConsentManager package you still have to inject analytics script tag into `<head>`. I don't know why but I missed it 🤷🏼‍♂️
